CREATE TABLE ANIMALS_DIM (
    animal_dim_id NUMBER(10) PRIMARY KEY,
    animal_id NUMBER(10),
    DATE_FROM DATE,
    DATE_TO DATE,
    hunt_id NUMBER(10),
    animal_name VARCHAR2(255),
    animal_description VARCHAR2(255),
    weight NUMBER(10),
    height NUMBER(10),
    price NUMBER(10)
);

CREATE SEQUENCE ANIMALS_DIM_S;
CREATE OR REPLACE TRIGGER ANIMALS_DIM_ON_INSERT
BEFORE INSERT ON ANIMALS_DIM
 FOR EACH ROW
BEGIN
 SELECT ANIMALS_DIM_S.NEXTVAL
 INTO :NEW.ANIMAL_DIM_ID
 FROM DUAL;
END;

CREATE TABLE Hunts (
    hunt_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DATE_FROM DATE,
    DATE_TO DATE,
    hunt_name VARCHAR2(255),
    hunt_description VARCHAR2(255),
    hunt_date DATE,
    location VARCHAR2(255),
    animals_hunted NUMBER(10),
    number_of_people NUMBER(10),
    duration NUMBER(10)
);
CREATE TABLE Animals (
    animal_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DATE_FROM DATE,
    DATE_TO DATE,
    hunt_id NUMBER(10),
    animal_name VARCHAR2(255),
    animal_description VARCHAR2(255),
    weight NUMBER(10),
    height NUMBER(10),
    price NUMBER(10)
);
CREATE TABLE Calendar (
    calendar_entry_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hunt_date DATE,
    duration_hours NUMBER(10)
);
CREATE TABLE Members (
    member_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hunt_id NUMBER(10),
    DATE_FROM DATE,
    DATE_TO DATE,
    name VARCHAR2(255),
    surname VARCHAR2(255),
    weight NUMBER(10),
    height NUMBER(10),
    age NUMBER(10),
    gender VARCHAR2(255),
    address VARCHAR2(255),
    email_address VARCHAR2(255),
    home_phone_number VARCHAR2(255),
    cell_mobile_phone_number VARCHAR2(255),
    FOREIGN KEY (hunt_id) REFERENCES Hunts(hunt_id)
);
CREATE TABLE Role (
    role_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DATE_FROM DATE,
    DATE_TO DATE,
    role_name VARCHAR2(255),
    role_description VARCHAR2(255)
);
CREATE TABLE Outcome (
    outcome_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DATE_FROM DATE,
    DATE_TO DATE,
    outcome_ending VARCHAR2(255),
    grade NUMBER(10)
);

CREATE TABLE Hunt_Meetings_Facts (
    hunt_meeting_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calendar_entry_id NUMBER(10),
    animal_id NUMBER(10),
    outcome_id NUMBER(10),
    hunt_id NUMBER(10),
    member_id NUMBER(10),
    role_id NUMBER(10),
    hunt_constant NUMBER(10,5), 
    total_number_of_people NUMBER(10), 
FOREIGN KEY (calendar_entry_id) REFERENCES Calendar(calendar_entry_id),
FOREIGN KEY (outcome_id) REFERENCES Outcome(outcome_id),
FOREIGN KEY (hunt_id) REFERENCES Hunts(hunt_id),
FOREIGN KEY (member_id) REFERENCES Members(member_id),
FOREIGN KEY (animal_id) REFERENCES Animals(animal_id),
FOREIGN KEY (role_id) REFERENCES Role(role_id)
);
