SELECT 
  ANIMALS.ANIMAL_ID,
  to_char(CATCHES.CATCH_DATE, 'yyyy-mm-dd') AS CATCH_DATE,
  ANIMALS.AGE AS AGE,
  ANIMALS.WEIGHT_KG AS WEIGHT_KG,
  ANIMALS.HEALTH_STATUS AS HEALTH_STATUS,
  10 - (5 - ANIMALS.HEALTH_STATUS/2) - (ANIMALS.AGE/(2*10)) AS MEAT_QUALITY,
  (10 - (5 - ANIMALS.HEALTH_STATUS/2) - (ANIMALS.AGE/(2*10))) / 2 + (ANIMALS.WEIGHT_KG / (2*10)) AS TROPHY_POINTS,
  ANIMALS.WEIGHT_KG * SPECIES.PRICE_PER_KG * ((1 - SPECIES.POPULATION_STATUS/10000) + 0.5) AS TOTAL_PRICE,
  CATCHES.CATCH_ID,
  SPECIES.SPECIE_ID,
  HUNTS.HUNT_ID,
  HUNTERS.HUNTER_ID,
  LOCATIONS.LOCATION_ID
FROM ANIMALS
INNER JOIN CATCHES ON CATCHES.CATCH_ID = ANIMALS.CATCH_ID
INNER JOIN SPECIES ON SPECIES.SPECIE_ID = ANIMALS.SPECIE_ID
INNER JOIN HUNTS ON HUNTS.HUNT_ID = CATCHES.HUNT_ID
INNER JOIN HUNTERS ON HUNTERS.HUNTER_ID = CATCHES.HUNTER_ID
INNER JOIN LOCATIONS ON LOCATIONS.LOCATION_ID = HUNTS.LOCATION_ID
