--------------------------------------------------------
--  File created - Friday-May-12-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table OUTCOME_DIM
--------------------------------------------------------

  CREATE TABLE "S17774"."OUTCOME_DIM" 
   (	"OUTCOME_DIM_ID" NUMBER(10,0), 
	"OUTCOME_ID" NUMBER(10,0), 
	"DATE_FROM" DATE, 
	"DATE_TO" DATE, 
	"OUTCOME_ENDING" VARCHAR2(255 BYTE), 
	"GRADE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS" ;
REM INSERTING into S17774.OUTCOME_DIM
SET DEFINE OFF;
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (38,37,to_date('11-MAY-23','DD-MON-RR'),null,'Magnificent',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (39,35,to_date('11-MAY-23','DD-MON-RR'),null,'Excellent',4);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (40,36,to_date('11-MAY-23','DD-MON-RR'),null,'Bad',3);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (41,44,to_date('11-MAY-23','DD-MON-RR'),null,'Bad',1);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (42,45,to_date('11-MAY-23','DD-MON-RR'),null,'Excellent',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (43,49,to_date('11-MAY-23','DD-MON-RR'),null,'Excellent',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (44,51,to_date('11-MAY-23','DD-MON-RR'),null,'Horrible',3);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (45,43,to_date('11-MAY-23','DD-MON-RR'),null,'Good',4);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (46,46,to_date('11-MAY-23','DD-MON-RR'),null,'Bad',1);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (47,47,to_date('11-MAY-23','DD-MON-RR'),null,'Super',4);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (48,39,to_date('11-MAY-23','DD-MON-RR'),null,'Extra',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (49,48,to_date('11-MAY-23','DD-MON-RR'),null,'Horrible',3);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (50,50,to_date('11-MAY-23','DD-MON-RR'),null,'Super',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (51,42,to_date('11-MAY-23','DD-MON-RR'),null,'Good',4);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (52,52,to_date('11-MAY-23','DD-MON-RR'),null,'Magnificent',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (53,53,to_date('11-MAY-23','DD-MON-RR'),null,'Horrible',3);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (54,54,to_date('11-MAY-23','DD-MON-RR'),null,'Magnificent',4);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (55,55,to_date('11-MAY-23','DD-MON-RR'),null,'Extra',4);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (56,58,to_date('11-MAY-23','DD-MON-RR'),null,'Super',4);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (57,56,to_date('11-MAY-23','DD-MON-RR'),null,'Super',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (58,57,to_date('11-MAY-23','DD-MON-RR'),null,'Extra',4);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (59,60,to_date('11-MAY-23','DD-MON-RR'),null,'Good',4);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (60,59,to_date('11-MAY-23','DD-MON-RR'),null,'Bad',1);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (61,61,to_date('11-MAY-23','DD-MON-RR'),null,'Excellent',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (62,62,to_date('11-MAY-23','DD-MON-RR'),null,'Horrible',3);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (63,63,to_date('11-MAY-23','DD-MON-RR'),null,'Super',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (64,64,to_date('11-MAY-23','DD-MON-RR'),null,'Bad',1);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (65,67,to_date('11-MAY-23','DD-MON-RR'),to_date('11-MAY-23','DD-MON-RR'),'Good',4);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (66,65,to_date('11-MAY-23','DD-MON-RR'),to_date('11-MAY-23','DD-MON-RR'),'Super',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (67,68,to_date('11-MAY-23','DD-MON-RR'),to_date('11-MAY-23','DD-MON-RR'),'Horrible',2);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (68,66,to_date('11-MAY-23','DD-MON-RR'),to_date('11-MAY-23','DD-MON-RR'),'Magnificent',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (69,69,to_date('11-MAY-23','DD-MON-RR'),to_date('11-MAY-23','DD-MON-RR'),'Good',4);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (70,70,to_date('11-MAY-23','DD-MON-RR'),to_date('11-MAY-23','DD-MON-RR'),'Good',4);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (71,71,to_date('11-MAY-23','DD-MON-RR'),to_date('11-MAY-23','DD-MON-RR'),'Magnificent',4);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (72,72,to_date('11-MAY-23','DD-MON-RR'),to_date('11-MAY-23','DD-MON-RR'),'Good',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (73,73,to_date('11-MAY-23','DD-MON-RR'),to_date('11-MAY-23','DD-MON-RR'),'Horrible',3);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (74,75,to_date('11-MAY-23','DD-MON-RR'),null,'Good',4);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (75,74,to_date('11-MAY-23','DD-MON-RR'),null,'Good',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (78,76,to_date('11-MAY-23','DD-MON-RR'),null,'Bad',1);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (79,77,to_date('11-MAY-23','DD-MON-RR'),null,'Bad',1);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (80,78,to_date('11-MAY-23','DD-MON-RR'),null,'Super',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (81,80,to_date('11-MAY-23','DD-MON-RR'),null,'Super',4);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (82,79,to_date('11-MAY-23','DD-MON-RR'),null,'Magnificent',4);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (83,81,to_date('11-MAY-23','DD-MON-RR'),null,'Magnificent',4);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (84,82,to_date('11-MAY-23','DD-MON-RR'),null,'Bad',1);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (85,83,to_date('11-MAY-23','DD-MON-RR'),null,'Bad',1);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (86,84,to_date('11-MAY-23','DD-MON-RR'),null,'Excellent',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (87,85,to_date('11-MAY-23','DD-MON-RR'),null,'Bad',1);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (89,86,to_date('11-MAY-23','DD-MON-RR'),null,'Extra',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (90,87,to_date('11-MAY-23','DD-MON-RR'),null,'Good',4);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (91,88,to_date('11-MAY-23','DD-MON-RR'),null,'Magnificent',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (92,89,to_date('11-MAY-23','DD-MON-RR'),null,'Magnificent',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (93,91,to_date('11-MAY-23','DD-MON-RR'),null,'Extra',4);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (94,90,to_date('11-MAY-23','DD-MON-RR'),null,'Extra',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (95,92,to_date('11-MAY-23','DD-MON-RR'),null,'Magnificent',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (96,93,to_date('11-MAY-23','DD-MON-RR'),to_date('11-MAY-23','DD-MON-RR'),'Excellent',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (97,96,to_date('11-MAY-23','DD-MON-RR'),to_date('11-MAY-23','DD-MON-RR'),'Super',4);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (98,94,to_date('11-MAY-23','DD-MON-RR'),to_date('11-MAY-23','DD-MON-RR'),'Bad',2);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (99,95,to_date('11-MAY-23','DD-MON-RR'),to_date('11-MAY-23','DD-MON-RR'),'Magnificent',4);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (100,97,to_date('11-MAY-23','DD-MON-RR'),to_date('11-MAY-23','DD-MON-RR'),'Magnificent',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (101,98,to_date('11-MAY-23','DD-MON-RR'),to_date('11-MAY-23','DD-MON-RR'),'Super',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (102,99,to_date('11-MAY-23','DD-MON-RR'),to_date('11-MAY-23','DD-MON-RR'),'Good',4);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (103,100,to_date('11-MAY-23','DD-MON-RR'),to_date('11-MAY-23','DD-MON-RR'),'Good',4);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (1,2,to_date('11-MAY-23','DD-MON-RR'),null,'Horrible',3);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (2,6,to_date('11-MAY-23','DD-MON-RR'),null,'Horrible',3);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (3,1,to_date('11-MAY-23','DD-MON-RR'),null,'Horrible',2);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (4,3,to_date('11-MAY-23','DD-MON-RR'),null,'Extra',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (5,5,to_date('11-MAY-23','DD-MON-RR'),null,'Super',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (6,4,to_date('11-MAY-23','DD-MON-RR'),null,'Excellent',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (7,10,to_date('11-MAY-23','DD-MON-RR'),null,'Horrible',2);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (8,13,to_date('11-MAY-23','DD-MON-RR'),null,'Super',4);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (9,7,to_date('11-MAY-23','DD-MON-RR'),null,'Horrible',3);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (10,9,to_date('11-MAY-23','DD-MON-RR'),null,'Super',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (11,11,to_date('11-MAY-23','DD-MON-RR'),null,'Excellent',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (12,8,to_date('11-MAY-23','DD-MON-RR'),null,'Magnificent',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (13,12,to_date('11-MAY-23','DD-MON-RR'),null,'Bad',1);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (14,14,to_date('11-MAY-23','DD-MON-RR'),null,'Bad',2);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (15,15,to_date('11-MAY-23','DD-MON-RR'),null,'Excellent',4);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (16,16,to_date('11-MAY-23','DD-MON-RR'),null,'Horrible',3);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (17,18,to_date('11-MAY-23','DD-MON-RR'),null,'Horrible',3);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (18,19,to_date('11-MAY-23','DD-MON-RR'),null,'Horrible',2);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (19,22,to_date('11-MAY-23','DD-MON-RR'),null,'Super',4);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (20,17,to_date('11-MAY-23','DD-MON-RR'),null,'Extra',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (21,20,to_date('11-MAY-23','DD-MON-RR'),null,'Bad',1);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (22,21,to_date('11-MAY-23','DD-MON-RR'),null,'Horrible',3);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (23,23,to_date('11-MAY-23','DD-MON-RR'),null,'Magnificent',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (24,26,to_date('11-MAY-23','DD-MON-RR'),null,'Magnificent',4);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (25,24,to_date('11-MAY-23','DD-MON-RR'),null,'Excellent',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (26,28,to_date('11-MAY-23','DD-MON-RR'),null,'Super',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (27,25,to_date('11-MAY-23','DD-MON-RR'),null,'Horrible',2);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (28,29,to_date('11-MAY-23','DD-MON-RR'),null,'Extra',2);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (29,30,to_date('11-MAY-23','DD-MON-RR'),null,'Magnificent',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (30,33,to_date('11-MAY-23','DD-MON-RR'),null,'Super',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (31,38,to_date('11-MAY-23','DD-MON-RR'),null,'Bad',3);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (32,27,to_date('11-MAY-23','DD-MON-RR'),null,'Magnificent',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (33,31,to_date('11-MAY-23','DD-MON-RR'),null,'Magnificent',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (34,32,to_date('11-MAY-23','DD-MON-RR'),null,'Extra',4);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (35,40,to_date('11-MAY-23','DD-MON-RR'),null,'Magnificent',4);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (36,34,to_date('11-MAY-23','DD-MON-RR'),null,'Excellent',5);
Insert into S17774.OUTCOME_DIM (OUTCOME_DIM_ID,OUTCOME_ID,DATE_FROM,DATE_TO,OUTCOME_ENDING,GRADE) values (37,41,to_date('11-MAY-23','DD-MON-RR'),null,'Bad',1);
--------------------------------------------------------
--  DDL for Index SYS_C00235659
--------------------------------------------------------

  CREATE UNIQUE INDEX "S17774"."SYS_C00235659" ON "S17774"."OUTCOME_DIM" ("OUTCOME_DIM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS" ;
--------------------------------------------------------
--  DDL for Trigger OUTCOME_DIM_ON_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "S17774"."OUTCOME_DIM_ON_INSERT" 
BEFORE INSERT ON OUTCOME_DIM
FOR EACH ROW
BEGIN
SELECT OUTCOME_DIM_S.NEXTVAL
INTO :NEW.OUTCOME_DIM_ID
FROM DUAL;
END;
/
ALTER TRIGGER "S17774"."OUTCOME_DIM_ON_INSERT" ENABLE;
--------------------------------------------------------
--  Constraints for Table OUTCOME_DIM
--------------------------------------------------------

  ALTER TABLE "S17774"."OUTCOME_DIM" ADD PRIMARY KEY ("OUTCOME_DIM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS"  ENABLE;
