--------------------------------------------------------
--  File created - Friday-May-12-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ROLE_DIM
--------------------------------------------------------

  CREATE TABLE "S17774"."ROLE_DIM" 
   (	"ROLE_DIM_ID" NUMBER(10,0), 
	"ROLE_ID" NUMBER(10,0), 
	"DATE_FROM" DATE, 
	"DATE_TO" DATE, 
	"ROLE_NAME" VARCHAR2(255 BYTE), 
	"ROLE_DESCRIPTION" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS" ;
REM INSERTING into S17774.ROLE_DIM
SET DEFINE OFF;
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (2,2,to_date('11-MAY-23','DD-MON-RR'),null,'Méryl','Topicort');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (3,5,to_date('11-MAY-23','DD-MON-RR'),null,'Stévina','METHADONE HYDROCHLORIDE');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (4,3,to_date('11-MAY-23','DD-MON-RR'),null,'Gaëlle','Pramipexole Dihydrochloride');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (5,4,to_date('11-MAY-23','DD-MON-RR'),null,'Pål','Morphine Sulfate');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (6,6,to_date('11-MAY-23','DD-MON-RR'),null,'Åslög','Orajel Instant Pain Relief');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (7,7,to_date('11-MAY-23','DD-MON-RR'),null,'Lén','Psorinoheel');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (8,8,to_date('11-MAY-23','DD-MON-RR'),null,'Nuó','Gelato Topical Anesthetic');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (37,37,to_date('11-MAY-23','DD-MON-RR'),null,'Rachèle','Topcare Sinus Congestion and Pain');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (38,38,to_date('11-MAY-23','DD-MON-RR'),null,'Renée','Tudorza Pressair');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (39,45,to_date('11-MAY-23','DD-MON-RR'),null,'Anaël','Piroxicam');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (40,39,to_date('11-MAY-23','DD-MON-RR'),null,'Cécilia','Strattera');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (1,1,to_date('11-MAY-23','DD-MON-RR'),null,'Méng','Ambien');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (9,9,to_date('11-MAY-23','DD-MON-RR'),null,'Estée','Arnica');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (10,10,to_date('11-MAY-23','DD-MON-RR'),null,'Bénédicte','Adenosine');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (11,11,to_date('11-MAY-23','DD-MON-RR'),null,'Göran','Mineral Oil');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (12,13,to_date('11-MAY-23','DD-MON-RR'),null,'Gaétane','Prostoforce');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (13,12,to_date('11-MAY-23','DD-MON-RR'),null,'Thérèsa','Isosorbide Dinitrate');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (14,14,to_date('11-MAY-23','DD-MON-RR'),null,'Mélia','Morphine Sulfate');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (15,15,to_date('11-MAY-23','DD-MON-RR'),null,'Marylène','Metaxalone');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (16,16,to_date('11-MAY-23','DD-MON-RR'),null,'Andréa','Head and Shoulders');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (17,17,to_date('11-MAY-23','DD-MON-RR'),null,'Illustrée','venlafaxine');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (18,18,to_date('11-MAY-23','DD-MON-RR'),null,'Maéna','FUCOIDAN SKINCURE');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (19,19,to_date('11-MAY-23','DD-MON-RR'),null,'Solène','Nan San MUSFLEX External Analgesic');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (20,20,to_date('11-MAY-23','DD-MON-RR'),null,'Andréa','Chloroquine');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (21,22,to_date('11-MAY-23','DD-MON-RR'),null,'Fèi','carbidopa, levodopa and entacapone');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (22,23,to_date('11-MAY-23','DD-MON-RR'),null,'Mårten','Keppra');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (23,21,to_date('11-MAY-23','DD-MON-RR'),null,'Maïté','Enoxaparin Sodium');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (24,24,to_date('11-MAY-23','DD-MON-RR'),null,'Ruò','Short Ragweed Pollen');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (25,25,to_date('11-MAY-23','DD-MON-RR'),null,'Andréa','BENZTROPINE MESYLATE');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (26,27,to_date('11-MAY-23','DD-MON-RR'),null,'Léa','Anti-Bacterial Hand');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (27,28,to_date('11-MAY-23','DD-MON-RR'),null,'Dorothée','Gentamicin');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (28,26,to_date('11-MAY-23','DD-MON-RR'),null,'Maëlyss','napoleon PERDIS CHINA DOLL FOUNDATION BROAD SPECTRUM SPF 15 Look 2');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (29,29,to_date('11-MAY-23','DD-MON-RR'),null,'Anaïs','Restless Legs Relief');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (30,30,to_date('11-MAY-23','DD-MON-RR'),null,'Mélys','Aveeno Positively Ageless');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (31,31,to_date('11-MAY-23','DD-MON-RR'),null,'Gaétane','Ethambutol Hydrochloride');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (32,32,to_date('11-MAY-23','DD-MON-RR'),null,'Océanne','Childrens ACCUDIAL');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (33,34,to_date('11-MAY-23','DD-MON-RR'),null,'Håkan','Lisinopril and Hydrochlorothiazide');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (34,33,to_date('11-MAY-23','DD-MON-RR'),null,'Renée','FAMILY CARE LUBRICANT SINGLE USE EYE');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (35,35,to_date('11-MAY-23','DD-MON-RR'),null,'Eloïse','Lisinopril and hydrochlorothiazide');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (36,36,to_date('11-MAY-23','DD-MON-RR'),null,'Maïlis','EpiPen');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (41,46,to_date('11-MAY-23','DD-MON-RR'),null,'Cloé','Armodafinil');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (42,40,to_date('11-MAY-23','DD-MON-RR'),null,'Anaïs','clindamycin phosphate');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (43,41,to_date('11-MAY-23','DD-MON-RR'),null,'Personnalisée','Moisture Therapy');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (44,42,to_date('11-MAY-23','DD-MON-RR'),null,'Judicaël','Clario Foaming Antibacterial Skin Cleanser');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (45,43,to_date('11-MAY-23','DD-MON-RR'),null,'Liè','Betaseron');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (46,44,to_date('11-MAY-23','DD-MON-RR'),null,'Adèle','Prednisone');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (47,47,to_date('11-MAY-23','DD-MON-RR'),null,'Séverine','good sense allergy and congestion relief');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (48,54,to_date('11-MAY-23','DD-MON-RR'),null,'Réjane','Prednisone');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (49,48,to_date('11-MAY-23','DD-MON-RR'),null,'Yè','Acyclovir');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (50,49,to_date('11-MAY-23','DD-MON-RR'),null,'Mélys','Gabapentin');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (51,50,to_date('11-MAY-23','DD-MON-RR'),null,'Eléa','Quinapril');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (52,51,to_date('11-MAY-23','DD-MON-RR'),null,'Lài','CHENOPODIUM ALBUM POLLEN');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (53,52,to_date('11-MAY-23','DD-MON-RR'),null,'Desirée','Levothyroxine Sodium');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (54,53,to_date('11-MAY-23','DD-MON-RR'),null,'Simplifiés','Aspirin');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (55,56,to_date('11-MAY-23','DD-MON-RR'),null,'Ráo','Pain Relieving');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (56,55,to_date('11-MAY-23','DD-MON-RR'),null,'Laïla','Oxycodone and Acetaminophen');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (57,57,to_date('11-MAY-23','DD-MON-RR'),null,'Léone','ENGLISH WALNUT');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (58,58,to_date('11-MAY-23','DD-MON-RR'),null,'Anaé','EnurAid');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (59,59,to_date('11-MAY-23','DD-MON-RR'),null,'Mélodie','Extra Strength Acetaminohpen');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (60,60,to_date('11-MAY-23','DD-MON-RR'),null,'Eloïse','Shopko Antibacterial Deep Cleansing Hand');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (61,61,to_date('11-MAY-23','DD-MON-RR'),null,'Marie-noël','Diclofenac Potassium');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (73,73,to_date('11-MAY-23','DD-MON-RR'),null,'Joséphine','EBSS-5');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (74,76,to_date('11-MAY-23','DD-MON-RR'),null,'Bécassine','Zyprexa');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (75,74,to_date('11-MAY-23','DD-MON-RR'),null,'Dafnée','CHENOPODIUM AMBROSIOIDES POLLEN');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (76,77,to_date('11-MAY-23','DD-MON-RR'),null,'Dù','Pain Relieving');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (77,75,to_date('11-MAY-23','DD-MON-RR'),null,'Personnalisée','Prednisone');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (78,78,to_date('11-MAY-23','DD-MON-RR'),null,'Régine','Pioglitazone');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (79,81,to_date('11-MAY-23','DD-MON-RR'),null,'Léonore','Sore Throat');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (80,79,to_date('11-MAY-23','DD-MON-RR'),null,'Aí','ENALAPRILAT');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (81,80,to_date('11-MAY-23','DD-MON-RR'),null,'Bénédicte','Opahl');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (82,82,to_date('11-MAY-23','DD-MON-RR'),null,'Styrbjörn','HyQvia');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (83,83,to_date('11-MAY-23','DD-MON-RR'),null,'Léonie','Alcohol Swabs with Benzocaine');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (84,84,to_date('11-MAY-23','DD-MON-RR'),null,'Illustrée','Cover Fx Blemish Treatment Concealer G Medium');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (85,85,to_date('11-MAY-23','DD-MON-RR'),null,'Agnès','Cyclopentolate Hydrochloride');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (86,86,to_date('11-MAY-23','DD-MON-RR'),null,'Åke','BARACLUDE');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (87,87,to_date('11-MAY-23','DD-MON-RR'),null,'Maéna','7 Select Childrens Pain Relief');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (88,91,to_date('11-MAY-23','DD-MON-RR'),null,'Léane','ORIGINAL POWER HYDRO AMPOULE');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (89,95,to_date('11-MAY-23','DD-MON-RR'),null,'Eléonore','DIANEAL Low Calcium with Dextrose');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (90,88,to_date('11-MAY-23','DD-MON-RR'),null,'Josée','quetiapine fumarate');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (91,89,to_date('11-MAY-23','DD-MON-RR'),null,'Göran','Sepia comp.');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (92,90,to_date('11-MAY-23','DD-MON-RR'),null,'Sòng','Omega 3 Heat Therapy');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (93,92,to_date('11-MAY-23','DD-MON-RR'),null,'Séverine','Horse Epithelium');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (94,93,to_date('11-MAY-23','DD-MON-RR'),null,'Cunégonde','Clearasil Ultra');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (95,94,to_date('11-MAY-23','DD-MON-RR'),null,'Alizée','SULPHUR');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (96,98,to_date('11-MAY-23','DD-MON-RR'),null,'Annotés','HELLO FLAWLESS OXYGEN WOW Broad Spectrum SPF 25 BRIGHTENING MAKEUP - IM PLUSH AND PRECIOUS');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (97,96,to_date('11-MAY-23','DD-MON-RR'),null,'Daphnée','GAVIS-CARE ANTACID');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (98,97,to_date('11-MAY-23','DD-MON-RR'),null,'Dù','Equate Milk of Magnesia');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (99,99,to_date('11-MAY-23','DD-MON-RR'),null,'Cloé','EradiKate Facial Mask');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (100,100,to_date('11-MAY-23','DD-MON-RR'),null,'Lóng','Fluconazole');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (62,62,to_date('11-MAY-23','DD-MON-RR'),null,'Clélia','Robafen AC');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (63,64,to_date('11-MAY-23','DD-MON-RR'),null,'Marie-thérèse','Levetiracetam');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (64,65,to_date('11-MAY-23','DD-MON-RR'),null,'Åsa','FlexGen');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (65,63,to_date('11-MAY-23','DD-MON-RR'),null,'Marie-françoise','Cold and Flu Nighttime');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (66,70,to_date('11-MAY-23','DD-MON-RR'),null,'Hélèna','CRYSTAL MIRACLE MULTI');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (67,66,to_date('11-MAY-23','DD-MON-RR'),null,'Athéna','ESIKA');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (68,71,to_date('11-MAY-23','DD-MON-RR'),null,'Maëlla','Octisalate, Avobenzone, Homosalate, Octocrylene');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (69,67,to_date('11-MAY-23','DD-MON-RR'),null,'Chloé','Metoprolol Tartrate');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (70,68,to_date('11-MAY-23','DD-MON-RR'),null,'Mélodie','SUGAR FREE PSYLDEX');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (71,69,to_date('11-MAY-23','DD-MON-RR'),null,'Hélène','Isosorbide Dinitrate');
Insert into S17774.ROLE_DIM (ROLE_DIM_ID,ROLE_ID,DATE_FROM,DATE_TO,ROLE_NAME,ROLE_DESCRIPTION) values (72,72,to_date('11-MAY-23','DD-MON-RR'),null,'Vérane','Topcare Nite Time Day Time');
--------------------------------------------------------
--  DDL for Index SYS_C00235658
--------------------------------------------------------

  CREATE UNIQUE INDEX "S17774"."SYS_C00235658" ON "S17774"."ROLE_DIM" ("ROLE_DIM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS" ;
--------------------------------------------------------
--  DDL for Trigger ROLE_DIM_ON_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "S17774"."ROLE_DIM_ON_INSERT" 
BEFORE INSERT ON ROLE_DIM
FOR EACH ROW
BEGIN
SELECT ROLE_DIM_S.NEXTVAL
INTO :NEW.ROLE_DIM_ID
FROM DUAL;
END;
/
ALTER TRIGGER "S17774"."ROLE_DIM_ON_INSERT" ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLE_DIM
--------------------------------------------------------

  ALTER TABLE "S17774"."ROLE_DIM" ADD PRIMARY KEY ("ROLE_DIM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS"  ENABLE;
